### ISSUE TITLE
Fix all weird out parameters `int *ret` in the codebase

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Refer to https://github.com/apache/incubator-kvrocks/pull/1444#discussion_r1199580764.
> Maybe not related to this PR, but there are two points:
>
> - `ret` is not a descriptive word
> - `int` type is not fit here: the return variable `members.size()` is typed `size_t`, not `int`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by infdahai** [comment]
@PragmaTwice I find the statement `*output = redis::Integer(ret);` is used multiple times to return the result to the client in [cmd_set.cc](https://github.com/apache/incubator-kvrocks/blob/unstable/src/commands/cmd_set.cc).
https://github.com/apache/incubator-kvrocks/blob/fb0e3d42031a6e0691c7a736711d0a01d72bdb1a/src/server/redis_reply.h#L38-L41

Add the `Integer` func checks whether compatibility with `int` is required(Of course, `size_t` is right). I see src/types/*.h and many funcs with this situation use `int`.

**Comment by PragmaTwice** [comment]
`Integer` can accept all [integral types](https://en.cppreference.com/w/cpp/types/is_integral) as its input, which includes `size_t`.

So I think it is not an obstacle.

**Comment by jihuayu** [comment]
Hello, I want to try it.

**Comment by infdahai** [comment]
> Hello, I want to try it.

Go ahead. It seems you will replace the `int` type with a more precise type, specially `size_t`. Remove the unnecessary type casting.

**Comment by torwig** [comment]
@infdahai You mean `size_t` by typing `usize`?

**Comment by infdahai** [comment]
Typos. Thanks for pointing it out

**Comment by jihuayu** [comment]
This issue involves many files. Should I submit one PR with all of the changes?

**Comment by git-hulk** [comment]
Yes, it's fine since the change is intuitive.

**Comment by jihuayu** [comment]
I have read through the relevant code and have decided to make modifications according to the following rules:

### The files match `types/redis_*.h`

- For the function similar to [`Set#IsMember`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_set.h#L36) or [`String#SetNX`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_string.h#L47) that `ret` means the flag, I will change it to `int *flag`

- For the function similar to [`Set#Remove`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_set.h#L39) that `ret` means the number of removed elements, I will change it to `uint64_t *removed_cnt`

- For the function similar to [`List#Size`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_list.h#L36) that `ret` means the size of list, I will change it to `uint64_t *size`

- For the function similar to [`List#Size`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_list.h#L36) that `ret` means the size of list, I will change it to `uint64_t *size`

- For the function similar to [`String#IncrBy`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/types/redis_string.h#L50) that `ret` means the new value, I will change it to `int64_t *new_value`

- In cases where `ret` may be negative, I will set the type to `int*`.

### The files match `commands/cmd_*.cc`

I will change the type of `int ret` to the correct type, but I will **not change the variable name** because it represents the return value of the Redis command.

### The test files

I will change the type of `int ret` to the correct type, and I will decide whether to modify the variable name based on the situation.


### All files

I will remove all unnecessary `static_cast` statements.

**I will use `uint64_t`([`Metadata#size`](https://github.com/apache/incubator-kvrocks/blob/unstable/src/storage/redis_metadata.h#L121) type) as the type for length everywhere, instead of the `size_t`.**



Do you think these are acceptable? I would appreciate hearing your thoughts and opinions.

**Comment by PragmaTwice** [comment]
I think you can replace it with `bool` if the return variable is just a boolean value.

**Comment by jihuayu** [comment]
> I think you can replace it with `bool` if the return variable is just a boolean value.

Thank you for your suggestion. I will do that.

**Comment by infdahai** [comment]
@git-hulk it seems the issue should be closed?

**Comment by git-hulk** [comment]
@infdahai Yes, thanks for your reminder.
