### ISSUE TITLE
Change the default value of max-io-mb to 0(unlimited)

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

For now, the max-io-mb is 500MiB which may be too low for fast devices like NVMe SSD,
so it'd be better to set the io bandwidth to unlimited by default.

See: https://github.com/apache/kvrocks/blob/unstable/kvrocks.conf#L278

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
AFAIK, this config will not only impact the IO, it also impact the CPU, because compaction might consume some CPU quota.

TiKV has a default set and doc: https://github.com/tikv/tikv/blob/fb9a40d20dcfb9ceb7cecba9d471fa8575c05913/etc/config-template.toml#L593-L611 . And it's default 10GiB ( see https://docs.pingcap.com/tidb/stable/tikv-configuration-file#rate-bytes-per-sec )

Seems that we should testing on this? ( But set to 0 is ok to me on most cases )

**Comment by git-hulk** [comment]
@mapleFU Thanks for your input. I feel it's a bit hard to test since depends on the device bandwidth.

**Comment by mapleFU** [comment]
> Thanks for your input. I feel it's a bit hard to test since depends on the device bandwidth.

Since we enable auto-tune by default( https://github.com/apache/kvrocks/pull/1424/files ), I think set to 0 when auto tuning is ok to me . Otherwise, we might need to tell our users about that :-)
