### ISSUE TITLE
proposal: add the default pull request template

### ISSUE THREAD

**Issue by LykxSassinator** [apache/kvrocks#2073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I found that Kvrocks lacks of the template for building PRs. And I wanna know whether it's necessary to supply a standard template for contributors to build PRs.

IMO, it's recommended to support a PR template for developers and contributors to make the contribution with a canonicalized guiding.

### Solution

Supply the PR template.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Since you have an idea to propose, I'm OK to give it a review. But from my experience a longy template is simply ignored. The important part is the PR author remembers to describe their PR and sets up issue references.

Currently, I don't see an urgent necessary for setting such a template for Kvrocks.

**Comment by LykxSassinator** [comment]
Yep, I agree with it. It certainly depends on the self-disciplined manners of the PR author.

Fine, maybe it can be picked up later.
