### ISSUE TITLE
How is this possible with column families? Question1: why store the version in the metadata

### ISSUE THREAD

**Issue by hiqsociety** [apache/kvrocks#297]
with reference to storing version in the metadata, how is it possible that i delete the key, 
    
         with version we can fast delete the metadata and then recycle the others keys-values in compaction background threads. 
         
what i mean is, how is it possible that deleting metadata will also delete the versioning? afterall u still need to cycle through key|version|field to delete them so the value will be deleted too.

can anyone give a better idea how this is done?

how is the key => metadata linked? multi cf or multi layer cf doesnt seem to be possible.

is this key version field below in its own cf by itself?

+---------------+
key|version|field => |     value     |
+---------------+

````
Question1: why store the version in the metadata
we store the hash keys/values into single key-value, if the store millions of sub keys-values in one hash key . if user delete this key, the kvrocks must iterator millions of sub keys-values and delete, and it would cause performance problem. with version we can fast delete the metadata and then recycle the others keys-values in compaction background threads. the cost is those tombstone key would take some disk stroage. you can regard the version as atomic increment number, but it’s combined with timestamp.
````

**Comment by git-hulk** [comment]
I try to summary your questions, correct me if misunderstood:

**1. Why delete metadata would delete the subkeys all well?**


this question explained by how we read and write the `hash` key-value:

From the write side:

If the user sends the `HSET hash_key field value`, then kvrocks would lookup the metadata with the key `hash_key`, it would generate a new one if no exists.  The metadata format was like `flags|expire|version|size`(see: [metadata design](https://github.com/bitleak/kvrocks/blob/unstable/docs/metadata-design.md)) and the version was unique(you can regard it as a monolithic increase sequence number). Only the metadata key was deleted when the user deletes the hash key which we call it fast delete, and it would generate new metadata with a new version

From the read side：

When the user sends the `HGET hash_key field` then lookup the metadata as well,  then use the version in the metadata to compose the subkey(`key|version|field`) and look up the field value. So subkeys were not found if the metadata was deleted since the metadata lookup subkey with version. It's the reason why fast delete works.

Finally, we recycle those old versions key-values in the background compaction thread


**2. How is the key => metadata linked? multi cf or multi-layer cf doesn't seem to be possible**

> I didn't get the meaning of this one

**Comment by hiqsociety** [comment]
this is manual trigger by the auto background compaction thread? 
 ```` 
 Finally, we recycle those old versions key-values in the background compaction thread
 ````
basically u are saying u perform a "fast delete" BUT there's no overall cpu savings when it comes to complete deletion other than using the background deletion right?
 
i thought it's a CF deletion, no wonder i cant find anything much on it. this explanation is much "better".

**Comment by git-hulk** [comment]
No, background compaction was automatic

**Comment by hiqsociety** [comment]
ok thx
