### ISSUE TITLE
[NEW]Please support restore command

### ISSUE THREAD

**Issue by zhklcf** [apache/kvrocks#409]
Migration tools like redisshake usually use restore command to realize migration from redis to kvrocks。
Please support restore command。

**Comment by ShooterIT** [comment]
Thanks, I MUST say that it is hard for us to implement redis RESOTRE command, since the restored value is the serialization of redis key value i.e. RDB format , so we need to support parsing all redis types, moreover, the encoding of key value serialization also would change in the future.

I think we shouldn't do this in kvrocks core code. Maybe there is a tool which can change RESTORE value to redis command, or we use other tools?

**Comment by git-hulk** [comment]
Twemproxy and Codis also have the same issue, and RedisShake supports parsing the restore command to AOF: https://github.com/alibaba/RedisShake/wiki/FAQ#q-does-redisshake-supports-codis-and-twemproxy

**Comment by enjoy-binbin** [comment]
restore was added in #1684, will be released in the next version (or try it in the unsable branch)
