### ISSUE TITLE
[NEW] Could kvrocks support multi db paths

### ISSUE THREAD

**Issue by JackyLucifer** [apache/kvrocks#535]
**The problem/use-case that the feature addresses**
During use kvrocks, we found kvrocks always write data to one db path, this behavior is not friendly, we want to kvrocks could write data to different db paths.

**Description of the feature**
As we know, rocksdb support multi db paths, so we hope kvrovks also could support this feature, we could set multi db paths by `config set` or `function`, maybe could create new db path if data file size of current db path exceeds setting threshold value.

**Alternatives you've considered**

different namespaces have different db paths.

**Additional information**

_NULL_

中文描述

**功能解决的问题/用例**

rocksdb能够对多个目录下的数据进行读写

**功能描述**

在使用过程中发现，在长时间写入后，都是写入到一个rocksdb数据文件中，希望通过函数控制数据库路径，或者控制rocksdb数据库文件在多大之后新建目录进行新的数据写入

**你考虑过的替代方案**
每次新建一个namespace，就按照namespace的名字，在rocksdb指定目录创建一个文件夹，相关数据存储到指定目录
在读写某个namespcae目录数据的时候对应打开，长时间不没有操作则关闭

**其他信息**
无

**Comment by ShooterIT** [comment]
I think this idea makes sense. I ever also wanted to support it, this feature may bring many advantages
- If there are some small disks, we also could provide big db
- As we know, now there are many storage media with different speeds, such as AEP, SSD, HDD, we can store low level data on the fast storage, to gain better performance.
- In cloud environment, we could use local disk and remote storage simultaneously.

Some related problems
- Multi db paths bring troubles to maintain database storage.
- For backup, it may bring some problems, since we may not just use hard link for rocksdb backup
- Similar with backup, full replication needs also one checkpoint. And replica needs to handle how to store checkpoint of master.

PS: to acquire more people concerns, l add descriptions  in English, please correct me if I have misunderstandings

**Comment by JackyLucifer** [comment]
I see. Multipath database storage will cause other related problems
My requirement is to control the path to read the database through code
Is this feasible?
If you can, I hope to open it and dynamically modify the database path, so as to achieve my purpose

For example:
The database path in the configuration file is loaded by default, and redis and rocksdb data are synchronized
After modifying the database path, synchronize redis and rocksdb data again

明白了，多路径数据库存储存会产生其他先关问题
我这边的需求是想通过代码控制读取数据库的路径
这样是否可行？
如果可以希望能够开放出，动态修改数据库路径，从而达到我这种使用目的

例如：
默认加载配置文件中的数据库路径，redis与rocksdb数据同步
修改数据库路径后，再次同步redis与rocksdb数据

**Comment by ShooterIT** [comment]
Hi @JackyLucifer Even multi db paths solution has several problem we need to deal with, i think it make much sense, it is worth putting energy to dig into.
your requirement is much customized and trick, i don't think we could support it, you can implement it in your branch.

**Comment by JackyLucifer** [comment]
OK
