### ISSUE TITLE
Automatically publish the nightly version of kvrocks to docker hub in daily CI

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Refer to #689 and #691, since we build the nightly version of the docker image we can automatically publish it to some registries like the docker hub, e.g. some tags like `nightly`, `nightly-20220629`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
This may not be as trivial as it looks like, since we must decide whether this is an official docker image endorsed by the Kvrocks PMC. If so, then it's an Apache release that we should vote before release.

However, since it's nightly image only, I'd share you some other Apache projects practice that we can publish images automatically.

* https://issues.apache.org/jira/browse/FLINK-26214
* https://github.com/apache/flink-kubernetes-operator/pull/118
* https://cwiki.apache.org/confluence/display/INFRA/Github+Actions+to+DockerHub

**Comment by PragmaTwice** [comment]
> This may not be as trivial as it looks like, since we must decide whether this is an official docker image endorsed by the Kvrocks PMC. If so, then it's an Apache release that we should vote before release.
> 
> However, since it's nightly image only, I'd share you some other Apache projects practice that we can publish images automatically.
> 
> * https://issues.apache.org/jira/browse/FLINK-26214
> * [[FLINK-26214] Publish Docker images to GitHub Registry flink-kubernetes-operator#118](https://github.com/apache/flink-kubernetes-operator/pull/118)
> * https://cwiki.apache.org/confluence/display/INFRA/Github+Actions+to+DockerHub

So thanks, seems there are lots of similiar works.

**Comment by PragmaTwice** [comment]
Solved by #741, #746, #747 and #748.
