### ISSUE TITLE
Integrate Go cases into build scripts

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#813]
I think basically we can treat Go cases as a standalone module and write a `Makefile` to it for running linters and tests.

Then we wire it into the `x.py` script.

**Comment by PragmaTwice** [comment]
I am thinking whether the makefile is necessary, since it is just a test module and we already have `x.py` which is a general script for developers. 

If there are two scripts that need to be maintained, I think it might cause some confusion. The functionality of the makefile is not orthogonal to our current `x.py`, they have similiar capabilities.

**Comment by tisonkun** [comment]
@PragmaTwice you're right. Previously I'm thinking of adding linters for Go code and then build/test can depend on the lint task. Makefile does a good job for task dependencies while implementing it inside a script is awkward. However, now I believe we can run lint in another `x.py` command and there's no dependency between tasks to handle. So your patch is great.

**Comment by tisonkun** [comment]
Closed by #832.
